import type { Category } from '../types/ShoppingItem';

const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  Dairy: [
    'milk',
    'cheese',
    'butter',
    'yogurt',
    'curd',
    'cream',
    'paneer',
    'ghee',
    'dahi',
    'makhana',
    'margerine',
    'cottage cheese',
    'queso',
    'mantequilla',
    'leche',
    'fromage',
    'lait',
    'beurre',
    'yaourt',
    'दूध',
    'दही',
    'पनीर',
    'मक्खन',
    'घी',
  ],
  Produce: [
    'apple',
    'apples',
    'banana',
    'bananas',
    'orange',
    'oranges',
    'tomato',
    'tomatoes',
    'onion',
    'onions',
    'potato',
    'potatoes',
    'berry',
    'berries',
    'fruit',
    'fruits',
    'vegetable',
    'vegetables',
    'spinach',
    'lettuce',
    'grape',
    'grapes',
    'mango',
    'mangoes',
    'strawberry',
    'lemon',
    'lime',
    'cucumber',
    'garlic',
    'ginger',
    'pepper',
    'carrot',
    'carrots',
    'avocado',
    'peach',
    'pear',
    'सेब',
    'केला',
    'संतरे',
    'टमाटर',
    'प्याज',
    'आलू',
    'आम',
    'अंगूर',
    'गाजर',
    'पालक',
    'manzana',
    'plátano',
    'platano',
    'tomate',
    'cebolla',
    'patata',
    'fresa',
    'pomme',
    'banane',
    'oignon',
    'carotte',
  ],
  Bakery: [
    'bread',
    'loaf',
    'loaves',
    'bun',
    'buns',
    'croissant',
    'bagel',
    'cake',
    'muffin',
    'pastry',
    'toast',
    'tortilla',
    'pita',
    'baguette',
    'roti',
    'naan',
    'ब्रेड',
    'रोटी',
    'नान',
    'pan',
    'pain',
    'gâteau',
    'gateau',
  ],
  Snacks: [
    'chips',
    'pretzel',
    'popcorn',
    'cookie',
    'cookies',
    'chocolate',
    'candy',
    'cracker',
    'crackers',
    'nut',
    'nuts',
    'almonds',
    'cashew',
    'biscuit',
    'biscuits',
    'wafer',
    'snack',
    'snacks',
    'नमकीन',
    'बिस्किट',
    'काजू',
    'बादाम',
    'galletas',
    'chocolat',
    'patatas fritas',
    'bonbon',
  ],
  Beverages: [
    'water',
    'coffee',
    'tea',
    'juice',
    'soda',
    'cola',
    'drink',
    'drinks',
    'beer',
    'wine',
    'espresso',
    'latte',
    'chai',
    'lemonade',
    'tonic',
    'पानी',
    'चाय',
    'कॉफी',
    'जूस',
    'शरबत',
    'agua',
    'café',
    'cafe',
    'té',
    'te',
    'jugo',
    'refresco',
    'eau',
    'jus',
  ],
  Household: [
    'soap',
    'detergent',
    'paper towel',
    'napkin',
    'tissue',
    'tissues',
    'cleaner',
    'shampoo',
    'trash bag',
    'foil',
    'sponge',
    'bleach',
    'disinfectant',
    'toothpaste',
    'toothbrush',
    'साबुन',
    'सर्फ',
    'पेस्ट',
    'jabón',
    'jabon',
    'detergente',
    'champú',
    'champu',
    'savon',
    'dentifrice',
  ],
  Other: [],
};

/**
 * Automatically categorizes an item name into one of:
 * Dairy, Produce, Bakery, Snacks, Beverages, Household, or Other.
 */
export function categorizeItem(itemName: string): Category {
  const normalized = itemName.toLowerCase().trim();
  if (!normalized) return 'Other';

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS) as [
    Category,
    string[]
  ][]) {
    for (const keyword of keywords) {
      const lowerKw = keyword.toLowerCase();
      // Match exact word or substring
      const regex = new RegExp(`\\b${lowerKw}\\b`, 'i');
      if (regex.test(normalized) || normalized.includes(lowerKw)) {
        return category;
      }
    }
  }

  return 'Other';
}
